# fly.toml app configuration file generated for epic-gippity on 2023-12-12T15:03:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "epic-gippity"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[services.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
